[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower

build_flags = 
    -O2
    -fno-fast-math
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI
    -D__FREERTOS=1
    -DFREERTOS_ENABLED
    -DMAVLINK_DIALECT=common
    -I.pio/libdeps/pico/c_library_v2
    -I.pio/libdeps/pico/c_library_v2/common
    -Wno-address-of-packed-member
    -DMAVLINK_PARAMS_ENABLED
    -DconfigCHECK_FOR_STACK_OVERFLOW=2
    -DconfigUSE_MALLOC_FAILED_HOOK=1
lib_deps =
    bolderflight/Bolder Flight Systems SBUS @ ^8.1.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit HMC5883 Unified @ ^1.2.3
    adafruit/Adafruit BMP085 Unified @ ^1.1.2
    https://github.com/mavlink/c_library_v2.git


[platformio]
src_dir = src
test_dir = test

[env:native]
platform = native
test_framework = unity
build_flags =
    -DUNIT_TEST
    -DMAVLINK_PARAMS_ENABLED
    -I test/native_include
    -I src
    -I .pio/libdeps/native/c_library_v2
    -I .pio/libdeps/native/c_library_v2/common
lib_deps =
    https://github.com/mavlink/c_library_v2.git
test_build_src = false
