#ifndef AEROPICO_MAVLINK_COMMANDS_H
#define AEROPICO_MAVLINK_COMMANDS_H

#include <Arduino.h>

enum AeroPicoServiceCommand : uint16_t {
    AEROPICO_CMD_CAL_IMU = 1,
    AEROPICO_CMD_CAL_MAG = 2,
    AEROPICO_CMD_CAL_RC = 3,
    AEROPICO_CMD_SERVO_TEST = 4,
    AEROPICO_CMD_RC_MONITOR = 5,
    AEROPICO_CMD_SENSOR_CHECK = 6,
    AEROPICO_CMD_PREFLIGHT_CHECK = 7
};

enum AeroPicoServoTestSurface : uint8_t {
    AEROPICO_SERVO_TEST_SURFACES = 0,
    AEROPICO_SERVO_TEST_AILERON = 1,
    AEROPICO_SERVO_TEST_ELEVATOR = 2,
    AEROPICO_SERVO_TEST_RUDDER = 3,
    AEROPICO_SERVO_TEST_THROTTLE = 4
};

#endif
