// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// pwm_servo //
// --------- //

#define pwm_servo_wrap_target 0
#define pwm_servo_wrap 2
#define pwm_servo_pio_version 0

static const uint16_t pwm_servo_program_instructions[] = {
            //     .wrap_target
    0x8080, //  0: pull   noblock
    0xa027, //  1: mov    x, osr
    0x0042, //  2: jmp    x--, 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_servo_program = {
    .instructions = pwm_servo_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = pwm_servo_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pwm_servo_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_servo_wrap_target, offset + pwm_servo_wrap);
    return c;
}
#endif

